# Generated by Django 6.0.1 on 2026-05-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=8, unique=True, verbose_name='Время записи')),
                ('heart_rate', models.CharField(verbose_name='Частота сердечных сокращений')),
            ],
        ),
    ]
