# Generated by Django 6.0.1 on 2026-05-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Doctor's Name")),
                ('speciality', models.CharField(max_length=100, verbose_name="Doctor's Speciality")),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Patient's Name")),
                ('age', models.IntegerField(verbose_name='Patient Age')),
                ('contact_info', models.CharField(max_length=255, verbose_name="Patient's Contacts")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='healthcare.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_details', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthcare.patient', verbose_name='patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(auto_now_add=True, verbose_name='date_started')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.patient', verbose_name='patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.treatment', verbose_name='treatment')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(through='healthcare.PatientTreatment', to='healthcare.treatment', verbose_name='treatment '),
        ),
    ]
