# Generated by Django 6.0.1 on 2026-05-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='patienttreatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patienttreatment',
            name='treatment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientTreatment',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
