# Generated by Django 6.0.1 on 2026-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='name',
            new_name='treatment_name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Doctor's Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Patient's Name"),
        ),
    ]
